---
version: '3.7'

services:

  build:
    image: golang:1.16-alpine
    entrypoint: sh
    volumes:
        - ".:/app"
        - "/tmp:/tmp"

  cf-terraforming:
    build: .
    working_dir: /app
    volumes:
      - .:/app

