---
version: '3.7'

services:

  build:
    image: golang:1.16-alpine
    entrypoint: sh
    working_dir: /go/src/github.com/pr8kerl/cf-terraforming
    volumes:
        - ".:/go/src/github.com/pr8kerl/cf-terraforming"
        - "/tmp:/tmp"

  cf-terraforming:
    build: .
    working_dir: /app
    volumes:
      - .:/app

